taxi/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login', views.login, name='login'),
    path('register', views.inscription, name='register'),
    path('logout', views.logout, name='logout'),

    path('reservations', views.reservations, name='reservations'),
    path('reservations/nouveau', views.reservations_nouveau, name='reservations.nouveau'),
    path('reservations/nouveau/<int:programme_id>', views.reservations_nouveau_withID, name='reservations.nouveau_id'),
    path('reservations/aujourdhui', views.reservations_jour, name='reservations.jour'),
    path('reservations/historique', views.reservations_historique, name='reservations.historique'),
    path('reservations/<int:reservation_id>/', views.detail, name='detail'),

    path('employer', views.employer, name='employer'),
    path('employer/nouveau', views.employer_nouveau, name='employer.nouveau'),
    path('employer/detail/<int:employer_id>', views.employer_detail, name='employer.detail'),
    path('employer/salaire/<int:employer_id>', views.employer_salaire, name='employer.salaire'),

    path('expeditions', views.expedition, name='expeditions'),
    path('expeditions/nouveau', views.expedition_nouveau, name='expeditions.nouveau'),
    path('expeditions/terminer', views.expedition_terminer, name='expeditions.terminer'),
    path('expeditions/completer/<int:id>', views.expedition_complet, name='expeditions.completer'),
    path('expeditions/supprimer/<int:id>', views.expedition_supprimer, name='expeditions.supprimer'),


    path('programme', views.programme, name='programme'),
    path('programme/nouveau', views.programme_nouveau, name='programme.nouveau'),
    path('programme/supprimer/<int:reservation_id>/', views.programme_supprimer, name='programme.supprimer'),

    path('voiture', views.voiture, name='voiture'),
    path('voiture/nouveau', views.voiture_nouveau, name='voiture.nouveau'),
    path('voiture/supprimer/<int:reservation_id>/', views.voiture_supprimer, name='voiture.supprimer'),
    path('gestion', views.gestion, name='gestion'),

    #path('expeditions/nouveau', views.expedition_nouveau, name='expeditions.nouveau'),
    #path('expeditions/terminer', views.expedition_terminer, name='expeditions.terminer'),



    path('prendre/<int:reservation_id>/', views.prendre, name='prendre'),
    path('supprimer/<int:reservation_id>/', views.supprimer, name='supprimer'),
    path('refuser/<int:reservation_id>/', views.refuser, name='refuser'),
    path('terminer/<int:reservation_id>/', views.terminer, name='terminer'),
]

taxi3/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

                  path('admin/', admin.site.urls, name='admin'),
                  path('', include('taxi.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

taxi/models.py
import datetime

from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
# Create your models here.
from django.utils import timezone

TYPE_CHOICES = (
    ("CL", "Classique"),
    ("VIP", "VIP"),
)

JOURS_CHOICES = (
    ("0", "Lundi"),
    ("1", "Mardi"),
    ("2", "Mercredi"),
    ("3", "Jeudi"),
    ("4", "Vendredi"),
    ("5", "Samedi"),
    ("6", "Dimance"),
)

POSTE_CHOICES = (
    ("CHAUFFEUR", "Chauffeur"),
    ("GUICHETIER", "Guichetier"),
)

CHOICES_VILLE = (
    ("YDE","Yaounde"),
    ("DLA","Douala"),
    ("BAF","Baffoussam"),
    ("BDA","Bamenda"),
    ("BDJ","Bandjoun"),
)

CHOICES_HEURES = (
    ("6","6h"),
    ("10","10h"),
    ("14","14h"),
    ("19","19h"),
    ("22","22h"),
)

RESERVATION_STATUS = (
    ("ATTENTE", "Attente"),
    ("REFUSER", "Refuser"),
    ("ACCEPER", "Accepter"),
    ("EN COUR", "Encour"),
    ("TERMINER", "Terminer"),

)


class UserManager(BaseUserManager):
    def create_user(self, telephone, first_name, last_name, cni, password=None):
        if not telephone:
            raise ValueError('Users must have a phone number')
        if not first_name:
            raise ValueError('Users must have a first_name')
        if not last_name:
            raise ValueError('Users must have a last_name')

        user = self.model(
            telephone=telephone,
            first_name=first_name,
            last_name=last_name,
            cni=cni

        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, telephone, first_name, last_name, cni, password):
        user = self.create_user(
            telephone,
            first_name,
            last_name,
            cni,
            password=password,
        )
        user.is_superuser = True
        user.is_admin = True
        user.is_staff= True
        user.save(using=self._db)

        print(user.is_superuser);
        return user


class Utilisateur(AbstractUser):
    username = None
    email = None
    code = models.CharField(max_length=64)
    telephone = models.CharField(max_length=64, unique=True)
    cni = models.CharField(max_length=64, unique=True)
    is_admin = models.BooleanField(default=False)

    # matricule = models.CharField(max_length=8, blank=True, null=True)
    def est_employer(self):
        try:
            return self.employe is not None or self.is_superuser
        except:
            return False

    objects = UserManager()
    REQUIRED_FIELDS = ['first_name', 'last_name', 'cni']
    USERNAME_FIELD = 'telephone'
    EMAIL_FIELD = 'telephone'

    def __str__(self):
        return self.get_full_name()


class Employe(models.Model):
    user = models.OneToOneField(
        Utilisateur,
        on_delete=models.CASCADE
        # primary_key=True,
    )
    salaire = models.BigIntegerField(null=False, default='50000', )
    poste = models.CharField(max_length=32, null=False, choices=POSTE_CHOICES, default="CHAUFFEUR")
    date_embauche = models.DateField(default=timezone.now())

    def __str__(self):
        return self.user.get_full_name()


class Client(models.Model):
    user = models.OneToOneField(
        Utilisateur,
        on_delete=models.CASCADE,
        # primary_key=True,
    )

    def __str__(self):
        return self.user.get_full_name()


class Voiture(models.Model):
    chauffeur = models.OneToOneField(Employe, on_delete=models.SET_NULL, null=True, blank=True)
    marque = models.CharField(max_length=64)
    categorie = models.CharField(max_length=64)
    matricule = models.CharField(max_length=8, blank=False, null=False)
    places = models.IntegerField(default=70)
    places_occuper = models.IntegerField(default=0)
    created_at = models.DateTimeField('Created at', default=timezone.now)

    def __str__(self):
        return f"{self.marque} {self.categorie} {self.places} Places "

    def place_dispo(self):
        return self.places - self.places_occuper

    def est_plein(self):
        return self.places == self.places_occuper

class Programme(models.Model):
    depart = models.CharField(max_length=64, choices=CHOICES_VILLE, null=False, )
    arrive = models.CharField(max_length=64, choices=CHOICES_VILLE, null=False, )
    type = models.CharField(max_length=64, choices=TYPE_CHOICES, null=False, default='CL')
    heure_depart = models.TimeField(max_length=64, default=datetime.time(15), )
    voiture = models.ForeignKey(Voiture, on_delete=models.SET_NULL, blank=True, null=True)
    tarif = models.IntegerField()

    def get_heure_depart_display(self):

        return f"{self.heure_depart.hour} H {self.heure_depart.minute if self.heure_depart.minute > 9 else '0'+str(self.heure_depart.minute)}" if self.heure_depart else "Pas d'horaire"
    def __str__(self):
        return f'Depart: {self.get_depart_display()}, Arrive: {self.get_arrive_display()}, Tarif: {self.tarif} FCFA, Heure: {self.get_heure_depart_display()}, Type: {self.get_type_display()}, Places: {self.voiture.place_dispo()}'

class Reservation(models.Model):
    programme = models.ForeignKey(Programme, on_delete=models.CASCADE, null=False, blank=False)
    places = models.IntegerField(default=1, validators=[
        MaxValueValidator(5),
        MinValueValidator(1)
    ])
    client = models.ForeignKey(Client, null=False, on_delete=models.CASCADE)

    guichetier = models.ForeignKey(Employe, null=True, on_delete=models.SET_NULL, default=None)
    created_at = models.DateTimeField('Created at', default=timezone.now())
    jour_depart = models.CharField(max_length=64, choices=JOURS_CHOICES, default=timezone.now().weekday())
    date_depart = models.DateField('Created at', default=timezone.now().date())
    statut = models.CharField(max_length=64, choices=RESERVATION_STATUS, null=False, default='ATTENTE')

    def __str__(self):
        return f"Client : {self.client.user}, Depart: {self.date_depart}, Par: {self.guichetier.user if self.guichetier else 'Aucun' }"

    def montant(self):
        return self.places * self.programme.tarif

    def _statut(self):
        return "En attente" if not self.guichetier else "Accepte"

    def est_aujourdhui(self):
        return (self.date_depart.day, self.date_depart.month, self.date_depart.year) == (timezone.now().day, timezone.now().month, timezone.now().year)

class Colis(models.Model):
    nom = models.CharField(max_length=64, null=False, )
    client = models.ForeignKey(Client, null=False, on_delete=models.CASCADE)

class Expedition(models.Model):
    colis = models.ForeignKey(Colis, null=False, on_delete=models.CASCADE)
    depart = models.CharField(max_length=64, choices=CHOICES_VILLE, null=False, )
    arrive = models.CharField(max_length=64, choices=CHOICES_VILLE, null=False, )
    tarif = models.IntegerField()
    livree = models.BooleanField(default=False, blank=False)

taxi/forms.py
from django import forms

from .models import Reservation, Utilisateur


class PostForm(forms.ModelForm):

    class Meta:
        model = Reservation
        fields = ('programme', 'places')


class AuthForm(forms.ModelForm):
    class Meta:
        model = Utilisateur
        fields = ('telephone', 'password')

taxi/templates/taxi/admin/ajout-employe.html
{% extends 'taxi/admin/base.html' %}
{% block title %} NOUVEAU EMPLOYE{% endblock %}
{% block content %}
    {% load static %}

    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                            <span class="page-title-icon bg-gradient-primary text-white mr-2">
                                <i class="mdi mdi-account-multiple"></i>
                            </span> Employés </h3>
            <nav aria-label="breadcrumb">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">
                        <span></span>Ajouter un Employés <i
                            class="mdi mdi-alert-circle-outline icon-sm text-primary align-middle"></i>
                    </li>
                </ul>
            </nav>
        </div>

        <div class="row">
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Ajouter un employé</h4>
                        <form class="forms-sample" method="post" action="{% url "employer.nouveau" %}">
                            {% csrf_token %}
                            <div class="form-group row">
                                <label for="exampleInputUsername2"
                                       class="col-sm-3 col-form-label">Nom : </label>
                                <div class="col-sm-9">
                                    <input type="text" name="first_name" class="form-control" id="exampleInputUsername2"
                                           placeholder="Nom " required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="exampleInputEmail2"
                                       class="col-sm-3 col-form-label">Prenom : </label>
                                <div class="col-sm-9">
                                    <input type="text" name="last_name" class="form-control" id="exampleInputEmail2"
                                           placeholder="Prenom" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="exampleInputMobile"
                                       class="col-sm-3 col-form-label">Numero de Telephone</label>
                                <div class="col-sm-9">
                                    <input type="text" name="telephone" class="form-control" id="exampleInputMobile"
                                           placeholder="Numero de telephone" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="cni"
                                       class="col-sm-3 col-form-label">Numero de CNI</label>
                                <div class="col-sm-9">
                                    <input type="text" name="cni" class="form-control" id="cni"
                                           placeholder="Numero de CNI" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="exampleInputPassword2"
                                       class="col-sm-3 col-form-label">Poste</label>
                                <div class="col-sm-9">
                                    <select type="text" name="poste" class="form-control" id="exampleInputPassword2"
                                            placeholder="Poste">
                                        <option value="CHAUFFEUR" selected>Chauffeur</option>
                                        <option value="GUICHETIER">Guichetier</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="salaire"
                                       class="col-sm-3 col-form-label">Salaire</label>
                                <div class="col-sm-9">
                                    <input class="form-control" name="salaire" type="number" min="35000" value="35000"
                                           placeholder="Salaire"/>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="exampleInputPassword2"
                                       class="col-sm-3 col-form-label">Date d'embauche</label>
                                <div class="col-sm-9">
                                    <input class="form-control" name="date" type="date" placeholder="dd/mm/yyyy"/>
                                </div>
                            </div>

                            <button type="submit" class="btn btn-gradient-primary mr-2">Submit</button>
                            <button class="btn btn-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

taxi/templates/taxi/admin/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TALLA VOYAGE - {% block title %} Tableau de bord {% endblock %}</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static "assets/vendors/mdi/css/materialdesignicons.min.css" %}">
    <link rel="stylesheet" href="{% static "assets/vendors/css/vendor.bundle.base.css" %}">
    <link rel="stylesheet" href="{% static "styles/W3.css" %}">
    <link rel="stylesheet" href="{% static "styles/style.css" %}">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="{% static "assets/css/style.css" %}">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="{% static "assets/images/favicon.png" %}"/>
</head>
<body>
<div class="container-scroller">
    <!-- partial:partials/_navbar.html -->
    <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
        <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
            <a class="navbar-brand brand-logo" href="index.html"><img src="{% static "assets/images/logo.png" %}"
                                                                      alt="logo"/></a>
            <a class="navbar-brand brand-logo-mini" href="index.html"><img
                    src="{% static "assets/images/logo-mini.png" %}" alt="logo"/></a>
        </div>
        <div class="navbar-menu-wrapper d-flex align-items-stretch">
            <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                <span class="mdi mdi-menu"></span>
            </button>

            <ul class="navbar-nav navbar-nav-right">
                <li class="nav-item nav-profile dropdown">
                    <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-toggle="dropdown"
                       aria-expanded="false">
                        <div class="nav-profile-img">
                            <img src="{% static "assets/images/faces/user2.svg" %}" alt="image">
                            <span class="availability-status online"></span>
                        </div>
                        <div class="nav-profile-text">
                            <p class="mb-1 text-black">{{ user.get_full_name }}</p>
                        </div>
                    </a>
                    <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
{% if user.is_superuser %}
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="/admin">
                            <i class="mdi mdi-set mr-2 text-primary"></i> Admin Account </a>
                        {% endif %}

                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">
                            <i class="mdi mdi-logout mr-2 text-primary"></i> Signout </a>
                    </div>
                </li>
                <li class="nav-item d-none d-lg-block full-screen-link">
                    <a class="nav-link">
                        <i class="mdi mdi-fullscreen" id="fullscreen-button"></i>
                    </a>
                </li>

            </ul>
            <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
                    data-toggle="offcanvas">
                <span class="mdi mdi-menu"></span>
            </button>
        </div>
    </nav>

    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_sidebar.html -->
        <nav class="sidebar sidebar-offcanvas" id="sidebar">
            <ul class="nav">
                <li class="nav-item nav-profile">
                    <a href="#" class="nav-link">
                        <div class="nav-profile-image">
                            <img src="{% static "assets/images/faces/user2.svg" %}" alt="profile">
                            <span class="login-status online"></span>
                            <!--change to offline or busy as needed-->
                        </div>
                        <div class="nav-profile-text d-flex flex-column">

                            <span class="font-weight-bold mb-2">{{ user.get_full_name }}</span>
                            {% if user.is_superuser %}
                                <span class="text-secondary text-small">Chef D'agence</span>
                            {% elif user.est_employe %}
                                <span class="text-secondary text-small">{{ user.employe.get_poste_display }}</span>
                                {% else %}
                                <span class="text-secondary text-small">Client</span>
                            {% endif %}

                        </div>
                    </a>
                </li>
            {% if user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">
                        <span class="menu-title">Tableau de bord</span>
                        <i class="mdi mdi-home menu-icon"></i>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'gestion' %}">
                        <span class="menu-title">Gestion</span>
                        <i class="mdi mdi-truck menu-icon"></i>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'employer' %}">
                        <span class="menu-title">Employés</span>
                        <i class="mdi mdi-account-multiple menu-icon"></i>
                    </a>
                </li>

            {% endif %}
            <li class="nav-item">
                    <a class="nav-link" href="{% url 'reservations' %}">
                        <span class="menu-title">Reservations</span>
                        <i class="mdi mdi-ticket menu-icon"></i>
                    </a>
                </li>
             <li class="nav-item">
                    <a class="nav-link" href="{% url 'programme' %}">
                        <span class="menu-title">Programme</span>
                        <i class="mdi mdi-train menu-icon"></i>
                    </a>
                </li>


            {% if user.is_staff %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'expeditions' %}">
                        <span class="menu-title">Expedition</span>
                        <i class="mdi mdi-train-variant menu-icon"></i>
                    </a>

                </li>
            {% endif %}


            </ul>
        </nav>

        <!-- partial -->
        <div class="main-panel">

            {% block content %} {% endblock %}

            <!-- content-wrapper ends -->
            <!-- partial:partials/_footer.html -->
            <footer class="footer">
                <div class="d-sm-flex justify-content-center justify-content-sm-between">
                    <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2020 All rights reserved.</span>
                    <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">made with UY1 - Dept INFO - INFOL3</span>
                </div>
            </footer>
            <!-- partial -->
        </div>
        <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
</div>
<!-- container-scroller -->
<!-- plugins:js -->
<script src="{% static "assets/vendors/js/vendor.bundle.base.js" %}"></script>
<!-- endinject -->
<!-- Plugin js for this page -->
<script src="{% static "assets/vendors/chart.js/Chart.min.js" %}"></script>
<!-- End plugin js for this page -->
<!-- inject:js -->
<script src="{% static "assets/js/off-canvas.js" %}"></script>
<script src="{% static "assets/js/hoverable-collapse.js" %}"></script>
<script src="{% static "assets/js/misc.js" %}"></script>
<!-- endinject -->
<!-- Custom js for this page -->
<script src="{% static "assets/js/dashboard.js" %}"></script>
<script src="{% static "assets/js/todolist.js" %}"></script>
<!-- End custom js for this page -->
</body>
</html>

taxi/templates/taxi/admin/detail-employe.html
{% extends 'taxi/admin/base.html' %}
{% block title %} NOUVEAU EMPLOYE{% endblock %}
{% block content %}
    {% load static %}


    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                            <span class="page-title-icon bg-gradient-primary text-white mr-2">
                                <i class="mdi mdi-account-multiple"></i>
                            </span> Employés </h3>
            <nav aria-label="breadcrumb">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">
                        <span></span>Details <i
                            class="mdi mdi-alert-circle-outline icon-sm text-primary align-middle"></i>
                    </li>
                </ul>
            </nav>
        </div>

        <div class="row">
            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">


                        <div class="d-flex mt-5 align-items-top">
                            <img src="{% static 'assets/images/faces/user2.svg' %}" class="img-sm rounded-circle mr-3"
                                 alt="image">
                            <div class="mb-0 flex-grow">
                                <h5 class="mr-2 mb-2">{{ employee.user.get_full_name }}</h5>
                                <br>
                                <div class="d-flex align-items-center text-muted font-weight-light">
                                    <i class="mdi mdi-account-card-details
                                    icon-sm mr-2"></i>
                                    <span>{{ employee.get_poste_display }}</span>
                                </div>
                                <br>
                                <div class="d-flex align-items-center text-muted font-weight-light">
                                    <i class="mdi mdi-clock icon-sm mr-2"></i>
                                    <span>Embauché le {{ employee.date_embauche }}</span>
                                </div>

                                <br>
                                <div class="d-flex align-items-center text-muted font-weight-light">
                                    <i class="mdi mdi-cellphone icon-sm mr-2"></i>
                                    <span>+237 {{ employee.user.telephone }}<span>
                                </div>

                                <br>
                                <div class="d-flex align-items-center text-muted font-weight-light">
                                    <i class="mdi mdi-card icon-sm mr-2"></i>
                                    <span>No CNI {{ employee.user.cni }}<span>
                                </div>

                                <br><br>
                                <a href="{% url 'employer.salaire' employee.id %}" class="btn btn-gradient-primary mr-2">Generer le
                                    bulettin de paie</a>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

taxi/templates/taxi/admin/employe.html
{% extends 'taxi/admin/base.html' %}
{% block title %}{% endblock %}
{% block content %}
    {% load static %}

    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                            <span class="page-title-icon bg-gradient-primary text-white mr-2">
                                <i class="mdi mdi-account-multiple"></i>
                            </span> Ajouter un employés </h3>
            <nav aria-label="breadcrumb">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">
                        <span></span>Overview <i
                            class="mdi mdi-alert-circle-outline icon-sm text-primary align-middle"></i>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="row" id="proBanner">
            <div class="col-12">
                            <span class="d-flex align-items-center purchase-popup">
                                <p>Ajouter un employés ?</p>
                                <a href="{% url 'employer.nouveau' %}"
                                   class="btn ml-auto download-button">Ajouter</a>
                            </span>
            </div>
        </div>
        <div class="row">

            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title"> Listes des employés </h4>
                        </p>
                        <table class="table ">
                            <thead>
                            <tr>
                                <th> User</th>
                                <th> Nom</th>
                                <th> Poste</th>
                                <th> Salaire</th>
                                <th> Details</th>

                            </tr>
                            </thead>
                            <tbody>
                            {% for employee in employees %}
                                <tr>
                                    <td class="py-1">
                                        <img src="{% static "assets/images/faces/user2.svg" %}" alt="image"/>
                                    </td>
                                    <td> {{ employee.user.get_full_name }} </td>
                                    <td> {{ employee.poste }} </td>
                                    <td> FCFA {{ employee.salaire }} </td>
                                    <td><a href="{% url 'employer.detail' employee.id %}"><label
                                            class="badge badge-success col-sm-6">Info</label></a>
                                        <a href="{% url 'employer.salaire' employee.id %}"><label
                                                class="badge badge-danger col-sm-6">Bulettin de
                                            paie</label></a>
                                    </td>
                                </tr>
                            {% endfor %}
                            <tr>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}